package udev

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/MixaDoDs/hidpass/internal/model"
)

const (
	Header           = "# Generated by hidpass. Do not edit; edit /etc/hidpass/devices.json via hidpass.\n"
	DefaultRulesPath = "/etc/udev/rules.d/70-hidpass.rules"
	RulesFileName    = "70-hidpass.rules"
)

// ReloadCommands reloads rules, re-applies them to hidraw and usb nodes, and
// waits until udev has finished processing the generated change events.
// A bare `udevadm trigger` would re-enumerate the whole device tree.
var ReloadCommands = [][]string{
	{"control", "--reload-rules"},
	{"trigger", "--subsystem-match=hidraw", "--action=change"},
	{"trigger", "--subsystem-match=usb", "--action=change"},
	{"settle", "--timeout=5"},
}

func Generate(devices []model.AllowedDevice) ([]byte, error) {
	copyOf := append([]model.AllowedDevice(nil), devices...)
	for i := range copyOf {
		vid, pid, err := model.NormalizePair(copyOf[i].VID, copyOf[i].PID)
		if err != nil {
			return nil, fmt.Errorf("device %d: %w", i, err)
		}
		copyOf[i].VID, copyOf[i].PID = vid, pid
	}
	sort.Slice(copyOf, func(i, j int) bool { return copyOf[i].ID() < copyOf[j].ID() })
	var b bytes.Buffer
	b.WriteString(Header)
	b.WriteString("# Seat uaccess plus MODE on the granted VID:PID only. Chromium WebHID ignores POSIX ACLs.\n")
	for _, d := range copyOf {
		if d.Name != "" {
			fmt.Fprintf(&b, "# %s [%s]\n", safeComment(d.Name), safeComment(d.Category))
		}
		fmt.Fprintf(&b, "KERNEL==\"hidraw*\", SUBSYSTEM==\"hidraw\", ATTRS{idVendor}==\"%s\", ATTRS{idProduct}==\"%s\", MODE=\"0666\", TAG+=\"uaccess\", TAG+=\"udev-acl\"\n", d.VID, d.PID)
		fmt.Fprintf(&b, "SUBSYSTEM==\"usb\", ENV{DEVTYPE}==\"usb_device\", ATTR{idVendor}==\"%s\", ATTR{idProduct}==\"%s\", MODE=\"0666\"\n", d.VID, d.PID)
	}
	return b.Bytes(), nil
}

func safeComment(s string) string {
	return strings.Map(func(r rune) rune {
		if r == '\n' || r == '\r' || r == 0 {
			return ' '
		}
		return r
	}, s)
}

type Manager struct {
	RulesPath string
	Run       func(name string, args ...string) ([]byte, error)
}

func DefaultManager() Manager {
	return Manager{RulesPath: DefaultRulesPath, Run: func(name string, args ...string) ([]byte, error) {
		return exec.Command(name, args...).CombinedOutput()
	}}
}

// IsPersistentRulesPath reports whether path is a durable udev rules location.
// /etc/udev/rules.d is loaded automatically after reboot; /run/udev/rules.d is tmpfs.
func IsPersistentRulesPath(path string) bool {
	clean := filepath.ToSlash(filepath.Clean(path))
	if strings.Contains(clean, "/run/") {
		return false
	}
	return strings.Contains(clean, "/etc/udev/rules.d/") || strings.HasSuffix(clean, "/etc/udev/rules.d")
}

func (m Manager) Write(devices []model.AllowedDevice) error {
	b, err := Generate(devices)
	if err != nil {
		return err
	}
	dir := filepath.Dir(m.RulesPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create udev rules directory %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, ".70-hidpass.rules.*")
	if err != nil {
		return fmt.Errorf("create temporary rules file: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if err = tmp.Chmod(0644); err == nil {
		_, err = tmp.Write(b)
	}
	if err == nil {
		err = tmp.Sync()
	}
	if closeErr := tmp.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return fmt.Errorf("write rules: %w", err)
	}
	if err := os.Rename(tmpName, m.RulesPath); err != nil {
		return fmt.Errorf("install rules %s: %w", m.RulesPath, err)
	}
	return nil
}

func (m Manager) Remove() error {
	if strings.TrimSpace(m.RulesPath) == "" {
		return fmt.Errorf("udev rules path is empty")
	}
	if err := os.Remove(m.RulesPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove rules %s: %w", m.RulesPath, err)
	}
	return nil
}

func (m Manager) Reload() error {
	if m.Run == nil {
		return fmt.Errorf("udev command runner is nil")
	}
	// Trigger only hidraw and usb: a bare `udevadm trigger` re-emits uevents
	// for every device on the system, which is needlessly disruptive.
	for _, args := range ReloadCommands {
		out, err := m.Run("udevadm", args...)
		if err != nil {
			return fmt.Errorf("udevadm %s: %w: %s", strings.Join(args, " "), err, strings.TrimSpace(string(out)))
		}
	}
	return nil
}
